### ISSUE TITLE
Minor reply projection issues

### ISSUE THREAD

**Issue by Davoodeh** [Asncodes-80/mamad-req-pageeee#1]
It'll be nice to have an indicator for the HTTP status code that comes from the server.

Moreover, the reply body textbox does not clean up automatically when the server replies with an empty payload.

**Comment by Asncodes-80** [comment]
Yep. It prepared only in less than 5min for your task! If you want to use it more than once, I can develop that and make it more usefull for yours. Thansk for your posting issue.

**Comment by Asncodes-80** [comment]
This issue wasn't important for tested task. If users want we update this issue, because it's not final production ReqApp. I will update that by new feature.
